# -*- coding: utf-8 -*-
"""chemical_industry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHrdrxEy_AgacnOfW3sGIXJtijNvkE5U
"""

from google.colab import files
data=files.upload()

import pandas as pd
alarm=pd.read_excel("Historical Alarm Cases.xlsx")

alarm.info()

alarm.head()

alarm.drop(["Case No."],axis=1,inplace=True)

alarm.dropna()

alarm.info()

x=alarm[["Ambient Temperature( deg C)","Calibration(days)","Humidity(%)","H2S Content(ppm)","detected by(% of sensors)"]]

y=alarm["Spuriosity Index(0/1)"]

y.info()

x.info()

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

scalar=StandardScaler()
standard=scalar.fit_transform(x)

standard

scalar=pd.DataFrame(standard,columns=["Ambient Temperature( deg C)","Calibration(days)","Humidity(%)","H2S Content(ppm)","detected by(% of sensors)"])

scalar

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=60)

lg=LogisticRegression()

lg.fit(x_train,y_train)

predict=lg.predict(x_test)

accuracy_score(predict,y_test)

